### ISSUE TITLE
proposal: convert irc bold escape sequences

### ISSUE THREAD

**Issue by josuah** [aaronNGi/jj#8]
```
function parse_bold(s,
        tail)
{
        tail = s
        s = ""
        while (match(tail, "\002[^\002]*\002")) {
                s = s substr(tail, 1, RSTART - 1) "\033[1m"
                s = s substr(tail, RSTART + 1, RLENGTH - 2) "\033[m"
                tail = substr(tail, RSTART + RLENGTH)
        }
        return s tail
}
```

This function reads text with irc escape sequence, and returns the same string with the `^B` converted to `\033[1m` or `\033[m` (if beginning or end).

`Text with ^Bbold^B characters` -> `Text with \033[1mbold\033[m characters`

I let you decide whether and how to integrate it

**Comment by aaronNGi** [comment]
I made a similar client in the past where I fully supported all formatting codes but this time around I decided it's bloat. Do you encounter a lot of bold tags? I'd say it's mostly channel topics where you would encounter it, isn't it?

I'm still leaning towards not doing any parsing of the formatting codes but I will think about it.

**Comment by aaronNGi** [comment]
The code is nice but I decided against doing any formatting. If we support bold now, the next person might wan't underscore, so I will be strict and say no formatting at all to keep `jjp` as small as possible (unfortunately it has already grown larger than I'd like due to the timestamp portability stuff, but in that case it's a good price to pay).

**Comment by josuah** [comment]
wait that people ask for CTCP ;)

**Comment by aaronNGi** [comment]
The horror. I actually looked at CTCP a while ago and it's not pretty to say the least :D
